version: "3.9"
services:
  api:
    build: .
    container_name: api_c
    networks:
      - fullstack
    env_file:
      - .env
    ports:
      - '8082:8082'

  postgres:
    image: postgres:14-alpine
    container_name: "db"
    ports:
      - "8081:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack

    
volumes:
    database_dockerizing:
    api_volume:

networks:
    fullstack:
      driver: bridge
